# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set env output and package
      id: setenvo
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        echo "TAG_NAME=$(git rev-list --count HEAD)" >> $env:GITHUB_OUTPUT
        tar cvf AutoReset.tar /home/runner/work/AutoReset/AutoReset/bin/Debug/net6.0/AutoReset.* 
        Compress-Archive -Path /home/runner/work/AutoReset/AutoReset/bin/Debug/net6.0/AutoReset.*,AutoReset.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        prerelease: true
        tag_name: v${{ steps.setenvo.outputs.TAG_NAME }}
        name: Release v${{ steps.setenvo.outputs.TAG_NAME }}
        files: |
          AutoReset.tar
          AutoReset.zip
